excluded:
  - Carthage
  - Pods
  - DerivedData
included:
  - Source
disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list
  - trailing_whitespace
  - type_name
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - yoda_condition
  - line_length
custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning
attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
force_cast: warning
force_try: warning
function_body_length:
    warning: 60
identifier_name:
  allowed_symbols: "_"
  excluded:
    - i
    - id
    - x
    - y
    - z
indentation_width:
  indentation_width: 4
legacy_hashing: error
line_length:
  warning: 160
  error: 250
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
private_over_fileprivate:
  validate_extensions: true
vertical_whitespace:
  max_empty_lines: 2
